language: ruby
rvm:
- 2.2.2
services:
- postgresql
env:
- DB=postgres
- DB=sqlite
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bin/rake db:drop db:create db:migrate
- bin/rails db:migrate RAILS_ENV=test
- bundle exec rails test
deploy:
  on:
    condition: "$DB = postgres"
    provider: heroku
    app: mediaprog
    run: rake db:migrate
    api_key:
    secure: pDmf5E7E/prHLfLq8jKSF/Q7VVlKn/0mMYXXfe0p2UMb7FK4tp5qRSUPsUvcPYciO1xe5t5vyZrTSWGVl/DDmlcN+a/AgMLOR5BFQHswyvF15HwVMjygTT5aKZUtRUzULcGdlOJF5TIP+Wf/Qs8+fYfQkeQL390ZDJTLtBDmNu04gFL9dFaonw+ymLb8i0DTQjpcs8oLfg+1xG27UHBtnK3ptPrAn73u9vGCAh0j/MZsOgK2y4PGRqKb4Ecd4k5DPtiujP2JFGL806ntYirr4wbcJ0SC/88nAZdU/EG7Rmc4kQSY1zOhVBT/cIe8exEMHWvJUNS7QmgXNu7wVC3CEw+//Y7hCIDbC5QFgSVSpWi0prgJUt4prWmJKvUVJoRFIspkTxeaK3xy7upE8d7Exbd2IBuYNJRYE5+POj3jx9nMNbtmSo9QfSgTwaZ21qC8wq3JPSJSbFCYSFsun3mgoVLl3OXwHGdxHJjMcmN7/0r4pAKvoBdN1dRQ3v2/R3LVP9CVf/ZsCtTfK+AWYavBv4zIHOsbuxV6lBduqk81ukxE79JXUBiGCXO/gEJsDd1rJ6lFSyk/75Q5InNwF4MhRizOE1D/SzW/Kbu4Y8GJpN5cyBnMXE2DAO2D/ORBxPdqc3Q9aA/5v7U4yQHxIyJOBV9c96M9eTYJXMAdLOMdGGM=
