language: ruby
services:
- postgresql
env:
- DB=postgres
- DB=sqlite
before_install:
   - rvm install 2.2.2
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bin/rails db:migrate RAILS_ENV=test
- bundle exec rails test
deploy:
  on:
    condition: "$DB = postgres"
  provider: heroku
  app: mediaprogramming
  run: "rake db:migrate"
