# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e36e4b38bc847ca3f421832d35b28867ca190552a6a48ac114908e1f1c45afd78291d7942c6e6253e017b8425b7e0bca4e8427ece1ed14c98d32026f4da31f9

test:
  secret_key_base: 47ac9a94281cc36cb6cc6f4ee4fa329e5d10347fec9d868f110ba525910b140a3c16c0c4929cc42f34e089ab39c2983a1a5f3e3536b77fb24965696496b3570c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
